### ISSUE TITLE
Using this package?

### ISSUE THREAD

**Issue by vendethiel** [stibear/cl-discord#1]
Hi,

I'm looking for something like cl-discord, but it seems it's not usable yet?
I don't see any way to override the callbacks.

i.e.

```
(use-package :cl-discord)

(let ((*token* "....")
      (client (make-discord-client))
  (connect client)
  #|how to bind events?|#)
```

It'd be helpful to get some examples.
Thanks :).

**Comment by stibear** [comment]
```lisp
(setf *token* "...")
(defparameter *discord-client* (make-discord-client))

(on :message-create *discord-client*
    (lambda (d s)
      ...))

(defun main ()
  (as:with-event-loop ()
    (connect *discord-client*)))
```

**Comment by vendethiel** [comment]
Thank you very much. I will be trying this code and will come back to you if it worked (with docs)/didn't (a bug report).

**Comment by vendethiel** [comment]
That helped a lot, however the call to `cl-discord:connect` fails with a 

```
Unhandled CL+SSL:SSL-ERROR-VERIFY in thread #<SB-THREAD:THREAD
                                              "main thread" RUNNING
                                               {1002D9E9D3}>:
  SSL verify error: 20 X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY
```

I tried adding the .pem from https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/ to my `~/.ssh`  but it doesn't seem to help.

**Comment by vendethiel** [comment]
Ended up going for `SSL_CERT_FILE=... sbcl bot.lisp`.

The issue now is that the event loop instantly closes:

my code is

```lisp
(defparameter *discord-client* (cl-discord:make-discord-client))
(as:with-event-loop ()
  (cl-discord:on :message-create *discord-client*
                 (lambda (d s)
                   (describe d)
                   (describe s)))
  (cl-discord:connect *discord-client*))
```

I get this when running `sbcl --script main.lisp`:

```
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
Closed: (:CODE NIL :REASON NIL)
```

if I enable the debugger, I get

```
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "websocket client read thread" RUNNING {1008254DD3}>:
  Event loop not running. Start with function start-event-loop.
```

**Comment by vendethiel** [comment]
That is a very surprising error.

If my event loop is:

```lisp
(as:with-event-loop ()
  (cl-discord:connect *discord-client*)
  (princ 1)
  (sleep 50)
  (princ 2))
```

then I see

```
Connected.
1
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "websocket client read thread" RUNNING {1008254DD3}>:
  Event loop not running. Start with function start-event-loop.
2
```

Which means, somehow, that the event loop "stopped" before the code got out of `as:with-event-loop`. I'm surprised.

**Comment by vendethiel** [comment]
Okay, I understand now.

[`websocket-driver-client:start-connection`](https://github.com/fukamachi/websocket-driver/blob/b9205073469faa2d2bf21aa05d033618deb79990/src/ws/client.lisp#L112) starts a [new thread](https://github.com/fukamachi/websocket-driver/blob/b9205073469faa2d2bf21aa05d033618deb79990/src/ws/client.lisp#L181-L190).

The function that checks if the event loop runs, [`check-event-loop-running`](https://github.com/orthecreedence/cl-async/blob/master/src/event-loop.lisp#L16), uses `*event-base*`
However [`*event-base*` is thread-local](https://github.com/orthecreedence/cl-async/blob/master/src/event-loop.lisp#L93-L96), and since the event loop was initialized in the main thread, the websocket-client read thread doesn't have it.

Do you know how to fix this?

**Comment by vendethiel** [comment]
Still wondering if you know how to fix this?

**Comment by ghost** [comment]
in theory you should be able to do this with [bt::\*default-special-bindings\*](https://trac.common-lisp.net/bordeaux-threads/wiki/ApiDocumentation#default-special-bindings) however i am unable to make it work i suspect because of the usage of :initial_bindings to bt:make-thread 
[here](https://github.com/fukamachi/websocket-driver/blob/b9205073469faa2d2bf21aa05d033618deb79990/src/ws/client.lisp#L189
)  I suspect if @fukamachi had done something like [this](https://github.com/sionescu/bordeaux-threads/blob/master/test/bordeaux-threads-test.lisp#L68) for :initial_bindings it might have worked.  i can kind of make it work by overriding start-connection but then other stuff fails.  i think there must be a simpler solution.

**Comment by vendethiel** [comment]
@listp aah, so there might be a solution then... i guess i'll open an issue on websocket-driver. But before that, do you remember what other failures you encountered?

**Comment by ghost** [comment]
@vendethiel no just that

**Comment by vendethiel** [comment]
@listp Mhhh...
Even with the change you mentioned, I get this error

```lisp
Connected.
Unhandled TYPE-ERROR in thread #<SB-THREAD:THREAD
                                 "websocket client read thread" RUNNING
                                  {100821CFF3}>:
  The value NIL is not of type HASH-TABLE.

Backtrace for: #<SB-THREAD:THREAD "websocket client read thread" RUNNING {100821CFF3}>
0: (SB-KERNEL:%PUTHASH 15763440 NIL (:CALLBACK #<CLOSURE (LABELS CL-ASYNC::MAIN :IN CL-ASYNC:INTERVAL) {10083F782B}> :EVENT-CB NIL)) [tl,external]
1: (CL-ASYNC:DELAY #<CLOSURE (LABELS CL-ASYNC::MAIN :IN CL-ASYNC:INTERVAL) {10083F782B}> :TIME 165/4 :EVENT-CB NIL)
2: (CL-ASYNC:INTERVAL #<CLOSURE (LAMBDA NIL :IN CL-DISCORD.GATEWAY:START-HEARTBEAT) {10083F77DB}> :TIME 165/4 :EVENT-CB NIL)
3: (CL-DISCORD.GATEWAY:START-HEARTBEAT #<CL-DISCORD.GATEWAY:DISCORD-CLIENT {1006C1E2F3}> "{\"t\":null,\"s\":null,\"op\":10,\"d\":{\"heartbeat_interval\":41250,\"_trace\":[\"gateway-prd-main-2qhm\"]}}")
4: ((LAMBDA (CL-DISCORD.GATEWAY::MESSAGE) :IN CL-DISCORD.GATEWAY:CONNECT) "{\"t\":null,\"s\":null,\"op\":10,\"d\":{\"heartbeat_interval\":41250,\"_trace\":[\"gateway-prd-main-2qhm\"]}}")
5: ((LAMBDA (EVENT-EMITTER::LISTENER) :IN EVENT-EMITTER:EMIT) #S(EVENT-EMITTER::LISTENER :FUNCTION #<CLOSURE (LAMBDA (CL-DISCORD.GATEWAY::MESSAGE) :IN CL-DISCORD.GATEWAY:CONNECT) {1007FE7BDB}> :ONCE NIL))
```

Maybe I should also clone cl-async locally and add a few `(declare (optimize (debug 3)))`...

**Comment by vendethiel** [comment]
The lib also uses API v5, deprecated by now

That's not an issue per say. The real issue is the same I posted here ^.

**Comment by vendethiel** [comment]
@stibear Hi, are you doing anything in CL / Discord anymore?
